// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BusinessLogicTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class IntegrateTestFeatureFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "IntegrateTestFeature.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "IntegrateTestFeature", "\tIn order to \r\n\tAs a \r\n\tI want to ", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "IntegrateTestFeature")))
            {
                global::BusinessLogicTests.Features.IntegrateTestFeatureFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "DEVICE_SN",
                        "DEVICE_ID",
                        "DEVICE_TYPE"});
            table1.AddRow(new string[] {
                        "2018001",
                        "192.168.10.99",
                        "N"});
            table1.AddRow(new string[] {
                        "2018002",
                        "192.168.10.98",
                        "N"});
#line 7
testRunner.Given("設備清單為", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "DEVICE_SN",
                        "TARGET_NAME",
                        "TARGET_VALUE",
                        "IS_EXCEPTION"});
            table2.AddRow(new string[] {
                        "2018001",
                        "Traffic - Gi1/0/20 [traffic_in]",
                        "ALERT",
                        "true"});
#line 11
testRunner.Given("告警條件為", ((string)(null)), table2, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "RECORD_SN",
                        "DEVICE_SN",
                        "TARGET_NAME",
                        "IS_EXCEPTION"});
            table3.AddRow(new string[] {
                        "2018111200001",
                        "2018001",
                        "Traffic - Gi1/0/20 [traffic_in]",
                        "false"});
            table3.AddRow(new string[] {
                        "2018111200002",
                        "2018002",
                        "Traffic - Gi1/0/20 [traffic_in]",
                        "true"});
#line 14
testRunner.Given("前次監控訊息為", ((string)(null)), table3, "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Cacti_ALERT訊息")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "IntegrateTestFeature")]
        public virtual void Cacti_ALERT訊息()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cacti_ALERT訊息", null, ((string[])(null)));
#line 20
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 21
 testRunner.Given("偵測器\"Cacti\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 22
 testRunner.And("設備類型為\"N\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.And("原始訊息為\"{ \"id\":\"192.168.10.99\", \"target\": \"Traffic - Gi1/0/20 [traffic_in]\", \"actio" +
                    "n\":\"ALERT\", \"info\":\"current value is 5630.6207\",\"time\":\"2018/11/06 18:08:34\" }\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.When("執行EF作業", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "DEVICE_SN",
                        "DEVICE_ID",
                        "TARGET_NAME",
                        "TARGET_VALUE",
                        "TARGET_CONTENT",
                        "RECEIVE_TIME",
                        "IS_EXCEPTION"});
            table4.AddRow(new string[] {
                        "2018001",
                        "192.168.10.99",
                        "Traffic - Gi1/0/20 [traffic_in]",
                        "ALERT",
                        "current value is 5630.6207",
                        "2018/11/06 18:08:34",
                        "true"});
#line 25
 testRunner.Then("EF解析告警結果為", ((string)(null)), table4, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "DEVICE_SN",
                        "DEVICE_ID",
                        "TARGET_NAME",
                        "TARGET_VALUE",
                        "TARGET_CONTENT",
                        "RECEIVE_TIME",
                        "IS_EXCEPTION",
                        "IS_NOTIFICATION"});
            table5.AddRow(new string[] {
                        "2018001",
                        "192.168.10.99",
                        "Traffic - Gi1/0/20 [traffic_in]",
                        "ALERT",
                        "current value is 5630.6207",
                        "2018/11/06 18:08:34",
                        "true",
                        "true"});
#line 28
 testRunner.And("EF狀態通知結果為", ((string)(null)), table5, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Cacti_NORMAL訊息")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "IntegrateTestFeature")]
        public virtual void Cacti_NORMAL訊息()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cacti_NORMAL訊息", null, ((string[])(null)));
#line 32
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 33
 testRunner.Given("偵測器\"Cacti\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 34
 testRunner.And("設備類型為\"N\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
 testRunner.And("原始訊息為\"{ \"id\":\"192.168.10.98\", \"target\": \"Traffic - Gi1/0/20 [traffic_in]\", \"actio" +
                    "n\":\"NORMAL\", \"info\":\"current value is 5630.6207\",\"time\":\"2018/11/06 18:08:34\" }\"" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
 testRunner.When("執行EF作業", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "DEVICE_SN",
                        "DEVICE_ID",
                        "TARGET_NAME",
                        "TARGET_VALUE",
                        "TARGET_CONTENT",
                        "RECEIVE_TIME",
                        "IS_EXCEPTION"});
            table6.AddRow(new string[] {
                        "2018002",
                        "192.168.10.98",
                        "Traffic - Gi1/0/20 [traffic_in]",
                        "NORMAL",
                        "current value is 5630.6207",
                        "2018/11/06 18:08:34",
                        "false"});
#line 37
 testRunner.Then("EF解析告警結果為", ((string)(null)), table6, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "DEVICE_SN",
                        "DEVICE_ID",
                        "TARGET_NAME",
                        "TARGET_VALUE",
                        "TARGET_CONTENT",
                        "RECEIVE_TIME",
                        "IS_EXCEPTION",
                        "IS_NOTIFICATION"});
            table7.AddRow(new string[] {
                        "2018002",
                        "192.168.10.98",
                        "Traffic - Gi1/0/20 [traffic_in]",
                        "NORMAL",
                        "current value is 5630.6207",
                        "2018/11/06 18:08:34",
                        "false",
                        "true"});
#line 40
 testRunner.And("EF狀態通知結果為", ((string)(null)), table7, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
